//
//  OrderListInteractor.swift
//  loginext
//
//  Created by Tasin Zarkoob on 17/01/2020.
//  Copyright (c) 2020 Tasin Zarkoob. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol OrderListBusinessLogic {
    func fetchOrders(request: OrderList.GetAllOrders.Request)
}

protocol OrderListDataStore {
  var data: [Order] { get set }
}

class OrderListInteractor: OrderListBusinessLogic, OrderListDataStore {
    var data: [Order] = []
    
    var presenter: OrderListPresentationLogic?
    var worker: OrderListWorker?
    
    // MARK: Fetch Order List
    
    func fetchOrders(request: OrderList.GetAllOrders.Request) {
        worker = OrderListWorker()
        worker?.getOrderList(request: request, completion: { (response) in
            self.presenter?.updateOrderList(response: response)
        })
  }
}
