//
//  OrderListModels.swift
//  loginext
//
//  Created by Tasin Zarkoob on 17/01/2020.
//  Copyright (c) 2020 Tasin Zarkoob. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum OrderList {
    
    // MARK: Use cases
    enum GetAllOrders {
        struct Request {
            let agentID: Int
        }
        
        struct Response {
            let orders: [Order]
            let errorString: String?
        }
    }
    
}
