//
//  OrderListWorker.swift
//  loginext
//
//  Created by Tasin Zarkoob on 17/01/2020.
//  Copyright (c) 2020 Tasin Zarkoob. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class OrderListWorker {
    
    func getOrderList(request: OrderList.GetAllOrders.Request, completion: @escaping ((OrderList.GetAllOrders.Response) -> Void)) {
        // get agentID
        let _ = request.agentID // i am not using it for now. showing the example
        
        // get the order data from firebase
        FirebaseDBManager.shared.getAllOrders { (data) in
            let array = (data as! NSDictionary).allValues
            if let jsonData = try? JSONSerialization.data(withJSONObject: array, options: []) {
                if let orders = try? JSONDecoder().decode([Order].self, from: jsonData) {
                    completion(OrderList.GetAllOrders.Response(orders: orders, errorString: nil))
                } else {
                   completion(OrderList.GetAllOrders.Response(orders: [], errorString: "Failed to decode"))
                }
            }
        }
    }
}
