//
//  OrderListRouter.swift
//  loginext
//
//  Created by Tasin Zarkoob on 17/01/2020.
//  Copyright (c) 2020 Tasin Zarkoob. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol OrderListRoutingLogic {
    func routeToOrderDetails(order: Order)
}

protocol OrderListDataPassing {
  var dataStore: OrderListDataStore? { get }
}

class OrderListRouter: NSObject, OrderListRoutingLogic, OrderListDataPassing {
    weak var viewController: OrderListViewController?
    var dataStore: OrderListDataStore?
    
    // MARK: Routing
    func routeToOrderDetails(order: Order) {
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        if let controller = storyboard.instantiateViewController(identifier: "OrderDetails") as? OrderDetailsViewController {
            controller.order = order
            viewController?.navigationController?.pushViewController(controller, animated: true)
        }
    }
        
  
}
